development:
  password: shptka_b9cbf9ea2310f72d0849abc83e062566
  theme_id: 131601563907
  store: playground-for-devs.myshopify.com
  ignore_files:
    - settings_data.json
    # - "templates/*.json"
